[package]
name = "list_math"
version = "0.1.0"
authors = ["_jameson_"]
edition = "2018"
decsription = "a crate for doing math on a list"
licence = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
